python /home/y/yj171/DetectRL_my/Detectors/binoculars_evaluation_new.py --test_data_path /home/y/yj171/LLM_AI_detect/guava/text_content_small_size.json
python /home/y/yj171/DetectRL_my/Detectors/DetectGPT_evaluation_new_new.py --test_data_path /home/y/yj171/LLM_AI_detect/guava/text_content_small_size.json
python /home/y/yj171/DetectRL_my/Detectors/entropy_evaluation_new.py --test_data_path /home/y/yj171/LLM_AI_detect/guava/text_content_small_size.json
python /home/y/yj171/DetectRL_my/Detectors/Fast_DetectGPT_evaluation_new.py --test_data_path /home/y/yj171/LLM_AI_detect/guava/text_content_small_size.json
python /home/y/yj171/DetectRL_my/Detectors/likelihood_evaluation_new.py --test_data_path /home/y/yj171/LLM_AI_detect/guava/text_content_small_size.json
python /home/y/yj171/DetectRL_my/Detectors/logRank_evaluation_new.py --test_data_path /home/y/yj171/LLM_AI_detect/guava/text_content_small_size.json
python /home/y/yj171/DetectRL_my/Detectors/LRR_evaluation_new.py --test_data_path /home/y/yj171/LLM_AI_detect/guava/text_content_small_size.json
python /home/y/yj171/DetectRL_my/Detectors/NPR_evaluation_new.py --test_data_path /home/y/yj171/LLM_AI_detect/guava/text_content_small_size.json
python /home/y/yj171/DetectRL_my/Detectors/rank_evaluation_new.py --test_data_path /home/y/yj171/LLM_AI_detect/guava/text_content_small_size.json